name: Setup
description: Setup for node
inputs:
  node-version:
    required: false
    description: Node version for setup-node
    default: 20.x

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Install pnpm
      uses: pnpm/action-setup@v3

    - name: Set node version to ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install
      shell: bash
      run: pnpm install
