name: Setup
description: Setup for node
inputs:
  node-version:
    required: false
    description: Node version for setup-node
    default: 24.x

runs:
  using: composite

  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Set node version to ${{ inputs.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install
      shell: bash
      run: pnpm install
